### ISSUE TITLE
Error: Couldn't run netstat -ano: {}

### ISSUE THREAD

**Issue by Runaround** [lokenx/plexrequests-meteor#102]
I'm trying to install this on my Windows 2012 R2 server and it won't start after the clone. I'm getting the following error (I changed the username):
```
C:\plexrequests>meteor
[[[[[ C:\plexrequests ]]]]]

=> Started proxy.

C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x8
6_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: Couldn't run netstat -ano: {}
    at Object.Future.wait (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at findMongoPids (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:120:16)
    at findMongoAndKillItDead (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:236:14)
    at launchOneMongoAndWaitForReadyForInitiate (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:360:7)
    at launchMongo (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:612:7)
    at [object Object]._.extend._startOrRestart (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:712:19)

    at [object Object]._.extend.start (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:670:10)
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-all.js:199:26
    - - - - -
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\run-mongo.js:89:28
    at ChildProcess.exithandler (child_process.js:654:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by lokenx** [comment]
Please refer to issue #65 for assistance.
