### ISSUE TITLE
App crashing at startup

### ISSUE THREAD

**Issue by naisspas** [lokenx/plexrequests-meteor#280]
It was working before updating to the last version
```
No change detected for the collection tv
object with id fGgE8kxrFivPJbbmg is not valid. trying to migrate..
released expectedConstructor
createdAt expectedNumber

/home/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Date of request must be a number
    at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:407:1)
    at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:390:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:143:1)
    at packages/davidyaha_collection2-migrations/packages/davidyaha_collection2-migrations.js:156:1
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
    at validateCollection (packages/davidyaha_collection2-migrations/packages/davidyaha_collection2-migrations.js:114:1)
    at [object Object].registerMigration [as attachSchema] (packages/davidyaha_collection2-migrations/packages/davidyaha_collection2-migrations.js:45:1)
    at lib/collections/collections.js:397:1
    at lib/collections/collections.js:398:1
Exited with code: 8
Your application is crashing. Waiting for file change.`
```

**Comment by lokenx** [comment]
Could you zip and send me your db per chance? It's in `.meteor/local/db`. Not 100% sure what's causing that as I tested a bunch of different dbs with new one.

What version did you start using the app?

**Comment by naisspas** [comment]
I'm using a docker container for your application (aptalca/docker-plexrequests), and the startup script clone the master branch each time the container start (git clone https://github.com/lokenx/plexrequests-meteor.git).

I will 7zip the db (and the startup log) tomorrow, but I'm not able to join the gitter chatroom you give the  link (404 error).

**Comment by lokenx** [comment]
OK thanks, I'll spin up a docker tomorrow morning.

Sorry, this [link](https://gitter.im/lokenx/plexrequests-meteor) should work!

**Comment by lokenx** [comment]
Was an issue using an old database before a db schema was put in place, and an auto-migrate wasn't possible.
