### ISSUE TITLE
New Crash

### ISSUE THREAD

**Issue by Grimshad** [lokenx/plexrequests-meteor#310]
After using it for a very long time. All the sudden it started doing this:

`No change detected for the collection movies
No change detected for the collection tv
No change detected for the collection settings

C:\Users\Server\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
Error: A method named '/movies/insert' is already defined
    at livedata_server.js:1542:15
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object]._.extend.methods (livedata_server.js:1538:7)
    at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:927:1)
    at new Mongo.Collection (packages/mongo/collection.js:218:1)
    at lib/collections/collections.js:3:1
    at lib/collections/collections.js:417:1
    at C:\Databases\plexrequests\.meteor\local\build\programs\server\boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Server\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
Exited with code: 8
Your application is crashing. Waiting for file change.`

**Comment by Grimshad** [comment]
I fixed it. please disregard.
