### ISSUE TITLE
'error: TypeError: Cannot call method 'replace' of null' when summary not present

### ISSUE THREAD

**Issue by sammeachem** [lokenx/plexrequests-meteor#430]
For tv show 'outlander', search url http://api.tvmaze.com/search/shows?q=outlander (pastebin of response in case it changes http://pastebin.com/b0KeVRhs)
Looks like the summary element isn't present in the response, so it null pointers on 
`var overview = s.summary.replace(/<(?:.|\n)*?>/gm, '') || "No overview.";`
in server/methods/helpers/tv/tvmaze.js

`error: TypeError: Cannot call method 'replace' of null
    at [object Object].Meteor.methods.tvmaze (server/methods/helpers/tv/tvmaze.js:27:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:1611:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.apply (livedata_server.js:1610:45)
    at [object Object]._.extend.call (livedata_server.js:1553:17)
    at [object Object].Meteor.methods.searchContent (server/methods/search/searchContent.js:13:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)`

**Comment by rigrassm** [comment]
Good catch, going to add null field checking to my to-do list. Probably going to push the fix when I finish up adding Radarr support.

**Comment by rigrassm** [comment]
Forgot to mention that this was fixed with this (commit)[https://github.com/lokenx/plexrequests-meteor/commit/033bcc779b89513100710f7f68bb5f00d4477909] which was made available in release v1.15.7
