### ISSUE TITLE
Movie request

### ISSUE THREAD

**Issue by obouallou** [lokenx/plexrequests-meteor#439]
When auto approve is disabled, the following error happens :

```
I20170201-23:19:02.680(0)? Exception while invoking method 'requestMovie' TypeError: Cannot read property 'permAPPROVAL' of undefined
I20170201-23:19:02.685(0)?     at [object Object].Meteor.methods.requestMovie (app/server/methods/search/requestMovie.js:114:102)
I20170201-23:19:02.689(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20170201-23:19:02.694(0)?     at packages/ddp-server/livedata_server.js:711:19
I20170201-23:19:02.698(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170201-23:19:02.703(0)?     at packages/ddp-server/livedata_server.js:709:40
I20170201-23:19:02.707(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20170201-23:19:02.710(0)?     at packages/ddp-server/livedata_server.js:707:46
I20170201-23:19:02.714(0)?     at tryCallTwo (/opt/plexrequests/.meteor/local/isopacks/promise/npm/node_modules/promise/lib/core.js:45:5)
I20170201-23:19:02.717(0)?     at doResolve (/opt/plexrequests/.meteor/local/isopacks/promise/npm/node_modules/promise/lib/core.js:200:13)
I20170201-23:19:02.721(0)?     at new Promise (/opt/plexrequests/.meteor/local/isopacks/promise/npm/node_modules/promise/lib/core.js:66:3)

```

**Comment by rigrassm** [comment]
Try updating to v1.15.7+, recently pushed some changes that may have affected this.

**Comment by rigrassm** [comment]
Any update on this issue?

**Comment by rigrassm** [comment]
Closing due to no response. Reopen if the issue persists.

**Comment by DCMarine** [comment]
This issue is not resolved.
