### ISSUE TITLE
error on restarting of the meteor

### ISSUE THREAD

**Issue by tarnecki** [lokenx/plexrequests-meteor#471]
After 1st install all went well and started without any problems.
When i've tried to restart service (check if systemd setup works after following your instructions) i'm getting loads or errors). Hope fully you can assist?
`root@localhost:/opt/plexrequests# meteor &
[2] 4884
root@localhost:/opt/plexrequests#
root@localhost:/opt/plexrequests#
root@localhost:/opt/plexrequests#
[[[[[ /opt/plexrequests ]]]]]

=> Started proxy.
   Checking for accounts-google@1.1.2        \
   Checking for accounts-meetup@1.2.1        |
   Checking for autoupdate@1.3.12            /
   Checking for binary-heap@1.0.10           /
=> Started MongoDB.
   Downloading 134 packages                  \
root@localhost:/opt/plexrequests#
root@localhost:/opt/plexrequests#
root@localhost:/opt/plexrequests#
root@localhost:/opt/plexrequests#
   Downloading 134 packages                  |
   Downloading 134 packages                  /
   Downloading 134 packages                  /
   Downloading 134 packages                  /
   Downloading 134 packages                  -
   Downloading 134 packages                  \
   Downloading 134 packages                  \
root@localhost:/opt/plexrequests#
   Downloading 134 packages                  /
   Downloading 134 packages                  -

/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: spawn ENOMEM
  at errnoException (child_process.js:1011:11)
  at ChildProcess.spawn (child_process.js:958:11)
  at Object.exports.spawn (child_process.js:746:9)
  at [object Object]._.extend._spawn (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:248:31)
  at [object Object]._.extend.start (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:87:22)
  at [object Object]._.extend._runOnce (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:712:16)
  at [object Object]._.extend._fiber (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:845:28)
  at /root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:385:12
`
Why is it downloading everything again like with the 1st run?

**Comment by tarnecki** [comment]
changing ram from 1gb to 2gb worked :)
