### ISSUE TITLE
When auto approve is disabled an error occurs on v1.21.0

### ISSUE THREAD

**Issue by DCMarine** [lokenx/plexrequests-meteor#517]
When auto approve is disabled the following issues occurs:   

Branch: master
Version: v1.21.0

`Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.527(-5)? #033[39mException while invoking method 'requestMovie' TypeError: Cannot read property 'permAPPROVAL' of undefined
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.527(-5)? #033[39m    at [object Object].Meteor.methods.requestMovie (server/methods/search/requestMovie.js:115:1)
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.527(-5)? #033[39m    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.527(-5)? #033[39m    at livedata_server.js:708:19
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.528(-5)? #033[39m    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.528(-5)? #033[39m    at livedata_server.js:706:40
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.528(-5)? #033[39m    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.529(-5)? #033[39m    at livedata_server.js:704:46
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.529(-5)? #033[39m    at tryCallTwo (/home/plex/.meteor/packages/promise/.0.5.1.dqgple++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.529(-5)? #033[39m    at doResolve (/home/plex/.meteor/packages/promise/.0.5.1.dqgple++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
Jan  7 18:53:57 requests meteor: #033[34mI20180107-18:53:57.529(-5)? #033[39m    at new Promise (/home/plex/.meteor/packages/promise/.0.5.1.dqgple++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.882(-5)? #033[39mException while invoking method 'requestMovie' TypeError: Cannot read property 'permAPPROVAL' of undefined
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.882(-5)? #033[39m    at [object Object].Meteor.methods.requestMovie (server/methods/search/requestMovie.js:115:1)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.882(-5)? #033[39m    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.882(-5)? #033[39m    at livedata_server.js:708:19
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.883(-5)? #033[39m    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.883(-5)? #033[39m    at livedata_server.js:706:40
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.883(-5)? #033[39m    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.883(-5)? #033[39m    at livedata_server.js:704:46
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.884(-5)? #033[39m    at tryCallTwo (/home/plex/.meteor/packages/promise/.0.5.1.dqgple++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.884(-5)? #033[39m    at doResolve (/home/plex/.meteor/packages/promise/.0.5.1.dqgple++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
Jan  7 18:53:59 requests meteor: #033[34mI20180107-18:53:59.884(-5)? #033[39m    at new Promise (/home/plex/.meteor/packages/promise/.0.5.1.dqgple++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
`

**Comment by scottyp89** [comment]
I'm getting the same sort of thing running in a Docker container on unRAID:

`Exception while invoking method 'requestMovie' TypeError: Cannot read property 'permAPPROVAL' of undefined
at [object Object].Meteor.methods.requestMovie (server/methods/search/requestMovie.js:115:1)
at maybeAuditArgumentChecks (livedata_server.js:1698:12)
at livedata_server.js:708:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:706:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:704:46
at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
at new Promise (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)`

I also have Plex authentication enabled if this makes a difference.

**Comment by viperxx** [comment]
I'm getting the same errors, also on 1.21.0, have plex authentication enabled as well. Works fine if I turn of approval, but I'd really like to use approval. I'm not using Sonarr or any other plugin.

```
I20180126-23:17:31.811(-5)? Sonarr Profiles Get -> ETIMEDOUT
I20180126-23:17:53.024(-5)? Exception while invoking method 'requestMovie' TypeError: Cannot read property 'permAPPROVAL' of undefined
I20180126-23:17:53.024(-5)?     at [object Object].Meteor.methods.requestMovie (app/server/methods/search/requestMovie.js:115:102)
I20180126-23:17:53.025(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20180126-23:17:53.025(-5)?     at packages/ddp-server/livedata_server.js:711:19
I20180126-23:17:53.025(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20180126-23:17:53.026(-5)?     at packages/ddp-server/livedata_server.js:709:40
I20180126-23:17:53.026(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20180126-23:17:53.027(-5)?     at packages/ddp-server/livedata_server.js:707:46
I20180126-23:17:53.027(-5)?     at tryCallTwo (/opt/plexrequests/.meteor/local/isopacks/promise/npm/node_modules/promise/lib/core.js:45:5)
I20180126-23:17:53.027(-5)?     at doResolve (/opt/plexrequests/.meteor/local/isopacks/promise/npm/node_modules/promise/lib/core.js:200:13)
I20180126-23:17:53.027(-5)?     at new Promise (/opt/plexrequests/.meteor/local/isopacks/promise/npm/node_modules/promise/lib/core.js:66:3)

```

**Comment by sethrd** [comment]
Same. 

```
Exception while invoking method 'requestTV' TypeError: Cannot read property 'permAPPROVAL' of undefined
    at [object Object].Meteor.methods.requestTV (server/methods/search/requestTV.js:82:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
    at new Promise (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```

Oddly, it only appears to be happening on TV requests. Movies still work fine. Running master, 1.21.1, from linuxserver.io's docker on unRAID.

**Comment by krh1009** [comment]
Same problem.  running in Unraid docker, approval required turned on.

`Exception while invoking method 'requestTV' TypeError: Cannot read property 'permAPPROVAL' of undefined
at [object Object].Meteor.methods.requestTV (server/methods/search/requestTV.js:82:1)
at maybeAuditArgumentChecks (livedata_server.js:1698:12)
at livedata_server.js:708:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:706:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:704:46
at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
at new Promise (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)`

**Comment by MystikIncarnate** [comment]
Same for me, getting the same error as sethrd  (others might match, his is just more legible), interspersed with my Exception is a "Sonarr Profiles Get -> ESOCKETTIMEOUT"  (we don't use Sonarr)  and "{ [Error: ESOCKETTIMEOUT] stack: [Getter] }" (there may be more to this but I'm missing lines from the display)

One of my users has been trying to submit a request and keeps getting a page for IRON:ROUTER coming up; no idea if that's related; I haven't done any customization of the Meteor package.  I've just run it and interfaced with it at the web UI.

Critical information: PlexRequests Version: 1.21.0 - VMware ESXi running Ubuntu 16.04 LTS.

I'm going to update to 1.21.2 and see if that makes a difference.  I'll report back if it does.

**Comment by MystikIncarnate** [comment]
seems to be resolved with 1.21.2.  Further testing may be required.  also looks like the Sonarr issues were a bugfix in 1.21.1 (according to the release notes).  I have the link to this thread so I'll be back if the issue reoccurs.

**Comment by lloyd094** [comment]
This error seemingly persists in mobile view (desktop works just fine).
