### ISSUE TITLE
Exception while invoking method 'checkPlexUser' TypeError: Cannot read property 'errors' of undefined

### ISSUE THREAD

**Issue by spuniun** [lokenx/plexrequests-meteor#527]
I'm not sure if this is related to the other Internal Server Error 500 on logins, but this one just started occurring for me recently, not back in Dec when it was reported.
`I20180227-15:46:11.551(-5)? Exception while invoking method 'checkPlexUser' TypeError: Cannot read property 'errors' of undefined
I20180227-15:46:11.552(-5)?     at MethodInvocation.plexLogin (app/server/methods/authentication/plexAuthentication.js:37:35)
I20180227-15:46:11.552(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180227-15:46:11.552(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
I20180227-15:46:11.552(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:46:11.553(-5)?     at resolve (packages/ddp-server/livedata_server.js:1684:36)
I20180227-15:46:11.553(-5)?     at new Promise (<anonymous>)
I20180227-15:46:11.553(-5)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
I20180227-15:46:11.553(-5)?     at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
I20180227-15:46:11.553(-5)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20180227-15:46:11.554(-5)?     at MethodInvocation.checkPlexUser (app/server/methods/authentication/plexAuthentication.js:53:35)
I20180227-15:46:11.554(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180227-15:46:11.554(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180227-15:46:11.554(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:46:11.554(-5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180227-15:46:11.555(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:46:11.555(-5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180227-15:46:11.555(-5)?     at new Promise (<anonymous>)
I20180227-15:46:11.555(-5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180227-15:46:11.555(-5)?     at packages/ddp-server/livedata_server.js:559:43
I20180227-15:46:11.556(-5)?  => awaited here:
I20180227-15:46:11.556(-5)?     at Promise.await (~/.meteor/packages/promise/.0.10.2.qi19pj.2dx3++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20180227-15:46:11.556(-5)?     at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
I20180227-15:46:11.556(-5)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20180227-15:46:11.556(-5)?     at MethodInvocation.checkPlexUser (app/server/methods/authentication/plexAuthentication.js:53:35)
I20180227-15:46:11.557(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180227-15:46:11.557(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180227-15:46:11.557(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:46:11.557(-5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180227-15:46:11.557(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:46:11.558(-5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180227-15:46:11.558(-5)?     at new Promise (<anonymous>)
I20180227-15:46:11.558(-5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180227-15:46:11.558(-5)?     at packages/ddp-server/livedata_server.js:559:43`
I'm guessing this was after a recent PMS update (1.11.3.4803) because users that were already logged in had no problems using Plex Requests, but users trying to authenticate anew got this 500 Error. Additionally, in admin if I try to re-authenticate the token I get the same/similar error
`I20180227-15:39:45.631(-5)? Exception while invoking method 'getPlexToken' TypeError: Cannot read property 'errors' of undefined
I20180227-15:39:45.632(-5)?     at MethodInvocation.plexLogin (app/server/methods/authentication/plexAuthentication.js:37:35)
I20180227-15:39:45.632(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180227-15:39:45.632(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
I20180227-15:39:45.632(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:39:45.632(-5)?     at resolve (packages/ddp-server/livedata_server.js:1684:36)
I20180227-15:39:45.632(-5)?     at new Promise (<anonymous>)
I20180227-15:39:45.633(-5)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
I20180227-15:39:45.633(-5)?     at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
I20180227-15:39:45.633(-5)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20180227-15:39:45.633(-5)?     at MethodInvocation.getPlexToken (app/server/methods/authentication/plexAuthentication.js:77:35)
I20180227-15:39:45.633(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180227-15:39:45.634(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180227-15:39:45.634(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:39:45.634(-5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180227-15:39:45.634(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:39:45.634(-5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180227-15:39:45.635(-5)?     at new Promise (<anonymous>)
I20180227-15:39:45.635(-5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180227-15:39:45.639(-5)?     at packages/ddp-server/livedata_server.js:559:43
I20180227-15:39:45.639(-5)?  => awaited here:
I20180227-15:39:45.640(-5)?     at Promise.await (/home/spuniun/.meteor/packages/promise/.0.10.2.qi19pj.2dx3++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20180227-15:39:45.640(-5)?     at Server.apply (packages/ddp-server/livedata_server.js:1635:14)
I20180227-15:39:45.640(-5)?     at Server.call (packages/ddp-server/livedata_server.js:1604:17)
I20180227-15:39:45.640(-5)?     at MethodInvocation.getPlexToken (app/server/methods/authentication/plexAuthentication.js:77:35)
I20180227-15:39:45.640(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20180227-15:39:45.641(-5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20180227-15:39:45.645(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:39:45.645(-5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20180227-15:39:45.646(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:26)
I20180227-15:39:45.646(-5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20180227-15:39:45.646(-5)?     at new Promise (<anonymous>)
I20180227-15:39:45.646(-5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20180227-15:39:45.646(-5)?     at packages/ddp-server/livedata_server.js:559:43`

Ubuntu 16.04.4 LTS
meteor 1.6.1
plexrequests master branch

**Comment by jamiehd** [comment]
I've been getting this issue and found it seems to be caused by entering an incorrect login.
