### ISSUE TITLE
Multiple issues with docker build

### ISSUE THREAD

**Issue by metrafonic** [lokenx/plexrequests-meteor#534]
Hello
I've been having multiple issues running the plexrequest docker build (pulled from the repo).
Starting the application works fine, but search is completely broken as well as trying to pull the plexpass token.
For example, when searching for a movie, this is shown in the logs:
```
dashboard_1  | info: First run complete
dashboard_1  | info: Updated TMDB image links
dashboard_1  | Exception while invoking method 'getVersion' Error: ENOENT, no such file or directory '/built_app/version.txt'
dashboard_1  |     at Object.fs.openSync (fs.js:439:18)
dashboard_1  |     at Object.fs.readFileSync (fs.js:290:15)
dashboard_1  |     at [object Object].Meteor.methods.getVersion (server/methods/admin/version.js:9:1)
dashboard_1  |     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
dashboard_1  |     at livedata_server.js:708:19
dashboard_1  |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
dashboard_1  |     at livedata_server.js:706:40
dashboard_1  |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
dashboard_1  |     at livedata_server.js:704:46
dashboard_1  |     at tryCallTwo (/built_app/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
dashboard_1  | Exception while invoking method 'checkForUpdate' Error: ENOENT, no such file or directory '/built_app/version.txt'
dashboard_1  |     at Object.fs.openSync (fs.js:439:18)
dashboard_1  |     at Object.fs.readFileSync (fs.js:290:15)
dashboard_1  |     at [object Object].Meteor.methods.getVersion (server/methods/admin/version.js:9:1)
dashboard_1  |     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
dashboard_1  |     at livedata_server.js:1611:18
dashboard_1  |     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
dashboard_1  |     at [object Object]._.extend.apply (livedata_server.js:1610:45)
dashboard_1  |     at [object Object]._.extend.call (livedata_server.js:1553:17)
dashboard_1  |     at [object Object].Meteor.methods.checkForUpdate (server/methods/admin/version.js:19:1)
dashboard_1  |     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
dashboard_1  | { [Error: connect ECONNREFUSED] stack: [Getter] }
dashboard_1  | error: TMDBSearch Error -> Cannot read property 'link' of undefined
```

It seems like the build is missing some files, such as `/built_app/version.txt`

This may also be a source of some of the other issues. Can anyone else confirm? 
Using the standard docker-compose file.

**Comment by metrafonic** [comment]
I am also having issues building the project:
```
Step 1/1 : RUN bash $METEORD_DIR/lib/build_app.sh
 ---> Running in 577512f32c08
=> Errors while initializing project:

While selecting package versions:
error: Package version not in catalog: aslagle:reactive-table 0.8.18

While refreshing package catalog to resolve previous errors:
error: DDP connection timed out

ERROR: Service 'dashboard' failed to build: The command '/bin/sh -c bash $METEORD_DIR/lib/build_app.sh' returned a non-zero code: 1
```

**Comment by rigrassm** [comment]
Hmm, I didn't create the dockerfile used for building the image so I'm not
familiar with how it's done. I honestly recommend using the linuxserver.io
image (I use use this myself) as it's always been well maintained and is
auto updated with every release.

**Comment by rigrassm** [comment]
Regarding the version related errors, those should be resolved in the next release along with a bunch of other stuff that i've been working on. See below for more details.

https://github.com/lokenx/plexrequests-meteor/issues/538#issuecomment-387687549
