### ISSUE TITLE
Error adding to Sonarr

### ISSUE THREAD

**Issue by ssn760** [lokenx/plexrequests-meteor#538]
As the title says, this is all I see in the Plex Requests logs.  I'm using the latest versions of both Plex Requests and Sonarr, inside docker containers provided by linuxserver.io ...

Plex Requests version - 1.21.2
Sonarr version 2.0.0.5163

I do not see any corresponding entry into the Sonarr logs.  When I run the connection test for Sonarr, the app reports success.  When I try to pull profiles from Sonarr, this also works correctly.

Is there a way to get more detail other than just "Error adding to Sonarr"?

**Comment by ssn760** [comment]
I halfway answered my own question by grabbing the console output from the docker container.  Here is that info:

Exception while invoking method 'getVersion' Error: ENOENT, no such file or directory '/app/bundle/version.txt'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at [object Object].Meteor.methods.getVersion (server/methods/admin/version.js:9:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/app/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
Exception while invoking method 'checkForUpdate' Error: ENOENT, no such file or directory '/app/bundle/version.txt'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at [object Object].Meteor.methods.getVersion (server/methods/admin/version.js:9:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
    at livedata_server.js:1611:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.apply (livedata_server.js:1610:45)
    at [object Object]._.extend.call (livedata_server.js:1553:17)
    at [object Object].Meteor.methods.checkForUpdate (server/methods/admin/version.js:19:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
Sonarr Series Post -> Match error: Expected string, got undefined

**Comment by ssn760** [comment]
FYI, I deleted the image & container and repulled, same issue manifests.

**Comment by goodpunk6** [comment]
I'm getting this error as well. I'm just trying to get sonarr and radarr to work with plex requests. i can add movies that I already have added in radarr or sonarr, but I can't request anything I new.

**Comment by rigrassm** [comment]
I've implemented a new wrapper around the "Check()" function that is notoriously horrible about providing details on what check failed and why, that will be able to provide the exact arguments that are failing the checks. This plus the work I started with overhauling the logging system to ensure that all log output is making it to the Admin -> Logs interface with much clearer and more detailed information than whats been available previously.

You can see a screenshot of the new log messages/format at the link below. Keep in mind I still have to go through a lot of code and replace the old logger functions with the module specific ones and rewrite the messages being sent as well. Still allot of work to do but once it's done it should make debugging much easier, especially for those that are unable to get console access and must rely on the Logs interface.

[Preview of the update Logs interface and message outputs.](https://imgur.com/a/6s229XY)
