### ISSUE TITLE
Error: MONGO_URL must be set in environment

### ISSUE THREAD

**Issue by SpacialDrift** [lokenx/plexrequests-meteor#555]
I get this constantly in my logs and the docker container will not start.  Any help/advise is appreciated.

`=> Starting meteor app on port:80

/built_app/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: MONGO_URL must be set in environment
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:36:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /built_app/programs/server/packages/accounts-base.js:1814:4
    at /built_app/programs/server/packages/accounts-base.js:1825:3
    at /built_app/programs/server/boot.js:242:10
    at Array.forEach (native)
`

This is inside a docker build running on a Synology DSM.

**Comment by bram-pkg** [comment]
You need to set the `MONGO_URL` environment variable to point to your MongoDB server.

Check this file for an example: https://github.com/lokenx/plexrequests-meteor/blob/master/docker-compose.yml
