### ISSUE TITLE
Radarr Post Error

### ISSUE THREAD

**Issue by ScapraraGit** [lokenx/plexrequests-meteor#563]
Hey guys-

Whenever a request is made, it looks like there are now incompatibilities with the latest version of Radarr. 

The request is added to Plex Requests, but never gets to Radarr. When reviewing the Admin logs it looks like:
`Post Error: failed [400] { "message": "BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.year | LineNumber: 0 | BytePositionInLine: 54.", "content": "Invalid request body. The JSON value could not be converted to System.Int32. Path: $.year | LineNumber: 0 | BytePositionInLine: 54." }`

When looking at the Radarr logs:
`2021-05-27 09:26:58.2|Info|RssSyncService|Starting RSS Sync
2021-05-27 09:27:00.8|Info|DownloadDecisionMaker|Processing 100 releases
2021-05-27 09:27:01.2|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
2021-05-27 09:40:44.7|Warn|RadarrErrorPipeline|API Error:
BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.year | LineNumber: 0 | BytePositionInLine: 54.

[v3.2.0.5048] Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.year | LineNumber: 0 | BytePositionInLine: 54.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)`

**Comment by beetus1actual** [comment]
I am also getting this same error when pressing the request button for a movie:

Radarr:
Version
3.2.1.5070

PlexRequests:
Version: v1.21.2

```
BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.year | LineNumber: 0 | BytePositionInLine: 48.

[v3.2.1.5070] Radarr.Http.REST.BadRequestException: BadRequest: Invalid request body. The JSON value could not be converted to System.Int32. Path: $.year | LineNumber: 0 | BytePositionInLine: 48.
   at Radarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate, Boolean skipSharedValidate) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 253
   at Radarr.Http.REST.RestModule`1.<set_CreateResource>b__43_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 206
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```
